Update wastage rates for Indian materials
arup-group/a-carbon-tool pull request #115
Opened 2022-02-28 14:15 UTC by Raj-P-Patel

Ticket reference - https://github.com/arup-group/a-carbon-tool/projects/1#card-78360155

- Updated wastage rates for Indian materials referring from WRAP Net Waste tool.
- Added/Updated Indian material factors based on available EPDs.

2022-02-28 15:19 UTC, tomhebunn requested changes

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +          wastage: 0.2,
Just checking - 0.2 is 20%. Is this correct?

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD of Average PPC and PSC Cement, ACC Limited 2018"
please can you add this EPD to your sources in the About section. Also worth reviewing to see if there has been an updated EPD. The shelf life of EPDs is typically 4 years and this may now be out of date

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD of Average PPC and Compocem Cement, Ambuja Cements Limited 2018"
see previous comment on referencing and shelf life

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD 12.5mm and 15mm Gypboard Plain, Gyproc, Saint Gobain 2018"
see above comment on referencing & shelf life

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "Berger External Thermal Insulation & Composite Systems (ETICS) EPD, Berger 2020"
please add EPD reference to About section

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD Average of Finished Long Products (Steel), JSW 2021"
please add EPD to About references

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD Average of Finished Flat Products (Steel), JSW 2022"
please add EPD reference to About section

2022-02-28 15:19 UTC, tomhebunn commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD Average of Finished Long Products (Steel), JSW 2021"
please add EPD reference to About section

2022-03-01 05:36 UTC, Raj-P-Patel reviewed
Thank you @tomhebunn. I have added the references for the EPDs to the data source. One of the EPDs (EPD 12.5mm and 15mm Gypboard Plain, Gyproc, Saint Gobain 2018) is nearing its validity - 04/12/2022. As of now, I couldn't find an updated version of the EPD.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +          wastage: 0.2,
Yes Tom. Have referred Table 2 from the WRAP NetWaste Tool: Guide to reference data
![brick_wastage](https://user-images.githubusercontent.com/60346651/156110221-cd2a4093-ec8f-4072-9549-97bca70f0098.PNG)
.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD of Average PPC and PSC Cement, ACC Limited 2018"
Thanks Tom, now added the reference to the source. This EPD is valid until 29/05/2023.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD of Average PPC and Compocem Cement, Ambuja Cements Limited 2018"
Now added the reference to the source. This EPD is valid until 21/06/2023.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD 12.5mm and 15mm Gypboard Plain, Gyproc, Saint Gobain 2018"
Now added the reference to the source. This EPD is valid until 04/12/2022. As of now I couldn't find an updated version of this EPD.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD 12.5mm and 15mm Gypboard Plain, Gyproc, Saint Gobain 2018"
Now added the reference to the source. This EPD is valid until 04/12/2022. As of now I couldn't find an updated version of this EPD.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "Berger External Thermal Insulation & Composite Systems (ETICS) EPD, Berger 2020"
Now added the reference to the source.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD Average of Finished Long Products (Steel), JSW 2021"
Now added the reference to the source.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD Average of Finished Flat Products (Steel), JSW 2022"
Now added the reference to the source.

2022-03-01 05:36 UTC, Raj-P-Patel commented on src/store/utilities/material-carbon-factors.ts
> +        source: "EPD Average of Finished Long Products (Steel), JSW 2021"
Now added the reference to the source.

2022-03-01 17:18 UTC, Exilliar commented
This looks all good to me from a code perspective, you should be good to merge when @tomhebunn approves

2022-03-02 10:59 UTC, merged