Arup server addition
arup-group/a-carbon-tool pull request #147
Opened 2022-03-14 18:13 UTC by tomhebunn

Added a means of manually defining speckle servers which are registered with ACT. Allows for registered servers to be hidden from general view in the app

2022-03-15 12:06 UTC, psarras requested changes
Hey! I tried to add the HS2 server, I authorized with my Arup credentials but I got the infamous `n/a` screen. I think this is related to running it on localhost? I seem to recall we were getting it on the production server but it was working on localhost, isn't this now the opposite situation? Can you confirm @Exilliar ?

Also after trying to return to the start page I got stacked into this page!

<img width="653" alt="image" src="https://user-images.githubusercontent.com/3820417/158373956-02842d1a-a479-4bd2-a767-0f5e2464a38e.png">

2022-03-15 12:11 UTC, Exilliar reviewed
Looking good! Put a couple of comments below, happy to have a call if you want to go through the smart vs dumb component thing.

I'm also getting the below errors in the console on the login page.
![Capture](https://user-images.githubusercontent.com/43271984/158369673-809160ac-f912-4ec3-b8d4-856f6aa8034f.PNG)

2022-03-15 12:14 UTC, Exilliar commented
> Hey! I tried to add the HS2 server, I authorized with my Arup credentials but I got the infamous `n/a` screen. I think this is related to running it on localhost? I seem to recall we were getting it on the production server but it was working on localhost, isn't this now the opposite situation? Can you confirm @Exilliar ?
> 
> Also after trying to return to the start page I got stacked into this page!
> 
> <img alt="image" width="653" src="https://user-images.githubusercontent.com/3820417/158373956-02842d1a-a479-4bd2-a767-0f5e2464a38e.png">

You might have got the n/a screen if you don't have the .env vars needed for the HS2 server. @tomhebunn have you made an app on the HS2 server that we can use? For prod we've been set up as a default app on all Arup Speckle servers (I think), I'm going to update the prod env vars soon to use the appid/secret from that app.

2022-03-15 16:23 UTC, tomhebunn commented on src/components/login/ArupLogin.vue
> +        arupAuth = true
removed. is a bit legacy and was trying to think about how we might allow users to select rather than define their server. Proved too difficult / unnecessary for now

2022-03-15 16:24 UTC, tomhebunn commented on src/components/login/LoginCard.vue
> +  servers = this.$store.state.servers
I only wanted to define the list of available servers once. Seemed clunky to define the format within each component

2022-03-15 16:25 UTC, tomhebunn commented on src/components/login/DefineLogin.vue
> +    servers = this.$store.state.servers
is there a way we can do this without having to define the format each time? Might become problematic when we add more servers

2022-03-15 16:25 UTC, tomhebunn commented on src/components/login/ArupLogin.vue
> +<template>
removed

2022-03-15 16:52 UTC, Exilliar commented on src/components/login/DefineLogin.vue
> +    servers = this.$store.state.servers
We should probably set up an interface for the servers object. Could put it in `models/shared/Servers.interface.ts`, then in that file do
```ts
import { Server } from "@/models/auth/";

export default interface Servers {
  arup: Server;
  xyz_server: Server;
  ...
}
```
Then we can use the interface from there rather than doing `{arup: Server; xyc_server: Server; ...}`. (so the above comment would become `@Prop() servers!: Servers`)

Would mean that when a server gets added we'd have to:
1. update the servers object to include the details of the server
2. update the interface to include the server

Having the interface does add a little bit of overhead, but it's not an unmanageable amount, and it gives us extra type checking, which is always good.

2022-11-03 14:05 UTC, Exilliar commented
closing as issue has been addressed in #171

2022-11-03 14:05 UTC, closed without merging