Dark mode
arup-group/a-carbon-tool pull request #49
Opened 2022-01-14 14:07 UTC by ro-sa

Implemented dark mode for both ARC and Vuetify. Please review:)

2022-01-17 09:52 UTC, psarras requested changes
Looking really great @ro-sa 

ome minor things: Why does the header animates when switching between modes but nothing else? Shall we keep it simple and remove the animation or at least match it? @tomhebunn  we never talked about the location of the buttons. Maybe let's add a setting page and put dark mode there?

2022-01-17 17:29 UTC, ro-sa commented
> 



> Looking really great @ro-sa
> 
> ome minor things: Why does the header animates when switching between modes but nothing else? Shall we keep it simple and remove the animation or at least match it? @tomhebunn we never talked about the location of the buttons. Maybe let's add a setting page and put dark mode there?

@psarras @tomhebunn 

Looks like the animation does not happen for text set as "secondary-text", so I presume it is to do with the default behaviour for primary text. If we want to stop the animation of the `<h1 class="text-h3 mb-5 mt-5">` then the style of the text changes and we would have to edit the theme/css to match what we have at the moment. I'm not sure we need these two titles to be so big, do we? Or is this part of the visual already set in stone?

2022-01-18 11:56 UTC, Exilliar approved these changes
got a couple of minor nitpick comments, but they're not worth blocking this pr over. I think that it's probably good to wait for Tom's pr (#51) to be merged in. Probably also good for @tomhebunn to have a look at this to check UI stuff

2022-01-18 11:56 UTC, Exilliar commented on src/assets/style.css
> +  /* --arc-brand-height: 3rem; */
if we're not using this it's probably a good idea to just delete this comment (sorry for the nitpick)

2022-01-18 11:56 UTC, Exilliar commented on src/store/index.ts
> +    setDarkMode(state) {
again, a very minor nitpick: might be good to change the name of this to `toggleDarkMode`. Not a neccessary change, just something if you have time

2022-01-18 12:14 UTC, ro-sa commented on src/assets/style.css
> +  /* --arc-brand-height: 3rem; */
agree. done

2022-01-18 12:19 UTC, ro-sa commented on src/store/index.ts
> +    setDarkMode(state) {
setDarkMode changes the darkMode state for the app as a whole. However, dark-mode is controlled from two separate places: 1. vuetify 2. arc => toggleDarkMode deals with both changing the global state (which controls vuetify) and the arc theme setting. I think it should stay as it is. Do you agree?

As a side note, this implementation feels a bit hacky since we're dealing with two tools controlling the dark-mode, but atm I don't see any value in trying to implement this differently. Open to opinions.

2022-01-18 18:12 UTC, psarras requested changes
I like the icon change and all the pages look good with the dark theme. 

Refreshing from light mode will reset to dark mode though.

2022-01-19 15:22 UTC, ro-sa commented
> I like the icon change and all the pages look good with the dark theme.
> 
> Refreshing from light mode will reset to dark mode though.

fixed using vuex-persistedstate

2022-01-20 14:14 UTC, psarras approved these changes
looking great @ro-sa !

2022-01-20 14:14 UTC, merged